# Generated by Django 5.2.3 on 2025-06-17 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RepoIdea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("repo_name", models.CharField(max_length=200)),
                ("summary", models.TextField()),
                ("ideas", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="IdeaDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idea_snippet", models.TextField()),
                ("detailed_info", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "repo_idea",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ideas_app.repoidea",
                    ),
                ),
            ],
        ),
    ]
