# Generated by Django 5.2.3 on 2025-06-17 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ideas_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ideadetail",
            name="groq_score",
            field=models.FloatField(
                blank=True,
                help_text="Score or ranking from Groq LLM evaluation",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="ideadetail",
            name="user_feedback",
            field=models.TextField(
                blank=True, help_text="User feedback or comments", null=True
            ),
        ),
        migrations.AddField(
            model_name="ideadetail",
            name="user_score",
            field=models.FloatField(
                blank=True, help_text="User assigned score or rating", null=True
            ),
        ),
        migrations.AddField(
            model_name="repoidea",
            name="groq_score",
            field=models.FloatField(
                blank=True,
                help_text="Score or ranking from Groq LLM evaluation",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="repoidea",
            name="user_feedback",
            field=models.TextField(
                blank=True, help_text="User feedback or comments", null=True
            ),
        ),
        migrations.AddField(
            model_name="repoidea",
            name="user_score",
            field=models.FloatField(
                blank=True, help_text="User assigned score or rating", null=True
            ),
        ),
    ]
