# Generated by Django 5.2.3 on 2025-06-17 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ideas_app", "0002_ideadetail_groq_score_ideadetail_user_feedback_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="repoidea",
            name="ideas",
        ),
        migrations.AlterField(
            model_name="ideadetail",
            name="detailed_info",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="ideadetail",
            name="repo_idea",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="idea_details",
                to="ideas_app.repoidea",
            ),
        ),
    ]
