# Generated by Django 5.2.3 on 2025-06-17 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ideas_app", "0004_alter_ideadetail_groq_score_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ideadetail",
            name="deep_dive_info",
            field=models.TextField(
                blank=True, help_text="Deeper analysis or exploration of the idea"
            ),
        ),
    ]
